[package]
name = "heltram"
version = "0.1.0"
authors = ["sprusr <scott@spru.sr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
